# Test environment configuration for FastMCP implementation
version: '3.8'

networks:
  test-network:
    driver: bridge

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql+asyncpg://test:test@postgres:5432/test_db
      - REDIS_URL=redis://redis:6379/2
      - MCP_SERVER_URL=http://mcp-server:8001
      - FASTMCP_TOKEN=ai_dev_MwUVUygQboY9yIeXQ539PYTJfv9Y7yeexWL4TrELMB8
      - JWT_SECRET_KEY=test-jwt-secret-key-for-testing-only-256-bits-long-exactly
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENVIRONMENT=testing
      - LOG_LEVEL=INFO
      - DEBUG=true
    depends_on:
      - postgres
      - redis
      - mcp-server
    networks:
      - test-network
    ports:
      - "8000:8000"
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level info
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mcp-server:
    build:
      context: .
      dockerfile: mcp_server/Dockerfile
    environment:
      - API_BASE_URL=http://app:8000
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8001
      - FASTMCP_LOG_LEVEL=DEBUG
      - LOG_LEVEL=DEBUG
      - DEBUG=true
    networks:
      - test-network
    ports:
      - "8001:8001"
    command: ["python", "mcp_server/auth_server.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    networks:
      - test-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    networks:
      - test-network
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5