"""add_member_management_system_models_and_fields

Revision ID: d59a7b4f8ccd
Revises: f51e6981ada8
Create Date: 2025-09-10 16:56:02.581150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59a7b4f8ccd'
down_revision = 'f51e6981ada8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invitations',
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization extending the invitation'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address of invited user'),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='organizationrole'), nullable=False, comment='Role to assign upon acceptance'),
    sa.Column('invited_by_id', sa.UUID(), nullable=False, comment='User who sent the invitation'),
    sa.Column('invitation_token', sa.String(length=255), nullable=False, comment='Secure token for invitation acceptance'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELLED', name='invitationstatus'), nullable=False, comment='Current invitation status'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When invitation expires (default 7 days)'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='When invitation was accepted'),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True, comment='When invitation was declined'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='When invitation was cancelled'),
    sa.Column('message', sa.String(length=1000), nullable=True, comment='Custom invitation message from inviter'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes'),
    sa.Column('extra_metadata', sa.Text(), nullable=True, comment='JSON metadata storage'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_created_at'), 'organization_invitations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_invitations_deleted_at'), 'organization_invitations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_invitation_token'), 'organization_invitations', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_organization_invitations_is_deleted'), 'organization_invitations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_status'), 'organization_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_organization_invitations_updated_at'), 'organization_invitations', ['updated_at'], unique=False)
    op.alter_column('organizations', 'domain',
               existing_type=sa.VARCHAR(length=255),
               comment='Primary domain for the organization (e.g., company.com) - multiple orgs can share domains',
               existing_comment='Primary domain for the organization (e.g., company.com)',
               existing_nullable=True)
    op.drop_index(op.f('ix_organizations_domain'), table_name='organizations')
    op.create_index(op.f('ix_organizations_domain'), 'organizations', ['domain'], unique=False)
    op.add_column('users', sa.Column('organization_role', sa.Enum('ADMIN', 'MEMBER', name='organizationrole'), nullable=True, comment="Role within the user's organization"))
    op.add_column('users', sa.Column('invited_by_id', sa.UUID(), nullable=True, comment='User who invited this member'))
    op.add_column('users', sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True, comment='When user was invited to organization'))
    op.add_column('users', sa.Column('joined_organization_at', sa.DateTime(timezone=True), nullable=True, comment='When user joined the organization'))
    op.create_foreign_key(None, 'users', 'users', ['invited_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'joined_organization_at')
    op.drop_column('users', 'invited_at')
    op.drop_column('users', 'invited_by_id')
    op.drop_column('users', 'organization_role')
    op.drop_index(op.f('ix_organizations_domain'), table_name='organizations')
    op.create_index(op.f('ix_organizations_domain'), 'organizations', ['domain'], unique=True)
    op.alter_column('organizations', 'domain',
               existing_type=sa.VARCHAR(length=255),
               comment='Primary domain for the organization (e.g., company.com)',
               existing_comment='Primary domain for the organization (e.g., company.com) - multiple orgs can share domains',
               existing_nullable=True)
    op.drop_index(op.f('ix_organization_invitations_updated_at'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_status'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_is_deleted'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_invitation_token'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_deleted_at'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_created_at'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    # ### end Alembic commands ###