"""allow_null_organization_id_for_system_agents

Revision ID: f51e6981ada8
Revises: dba8a43efbc8
Create Date: 2025-09-10 11:01:07.765805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51e6981ada8'
down_revision = 'dba8a43efbc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Allow NULL organization_id for system agents
    op.alter_column('agents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='Organization this agent belongs to (NULL for system agents)',
               existing_comment='Organization this agent belongs to')
    
    # Update existing system title agents to have NULL organization_id
    op.execute("""
        UPDATE agents 
        SET organization_id = NULL 
        WHERE agent_type = 'title_generation' 
          AND name = 'System Title Generator'
          AND is_deleted = false;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: This downgrade will fail if system agents exist with NULL organization_id
    # You must manually update or delete system agents before running this downgrade
    op.execute("""
        -- Delete system title agents with NULL organization_id before making column NOT NULL
        DELETE FROM agents 
        WHERE agent_type = 'title_generation' 
          AND organization_id IS NULL;
    """)
    
    # Restore NOT NULL constraint on organization_id
    op.alter_column('agents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Organization this agent belongs to',
               existing_comment='Organization this agent belongs to (NULL for system agents)')
    # ### end Alembic commands ###