"""complete_squashed_schema

Revision ID: 002_complete
Revises: 001_fresh
Create Date: 2025-10-01 15:55:31.766807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_complete'
down_revision = '001_fresh'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Organization this agent belongs to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Organization this agent belongs to')
    # ### end Alembic commands ###