"""Refactor thread_metadata to separate fields

Revision ID: 3d88613612bb
Revises: f1a2b3c4d5e6
Create Date: 2025-09-09 09:21:14.035805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d88613612bb'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only apply thread-related changes to fix the specific error
    op.add_column('threads', sa.Column('total_messages', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('threads', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    
    # Try to drop thread_metadata column if it exists
    try:
        op.drop_column('threads', 'thread_metadata')
    except Exception:
        # Column might not exist, ignore the error
        pass
        
    # Try to drop metadata column if it exists    
    try:
        op.drop_column('threads', 'metadata')
    except Exception:
        # Column might not exist, ignore the error
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only handle thread-related rollback
    op.add_column('threads', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('threads', 'last_message_at')
    op.drop_column('threads', 'total_messages')
    # ### end Alembic commands ###